name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test on Node 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx cypress install
      - run: npm run build # includes lint:ts
      - run: npm run test

      - name: Upload coverage report on Node 20 to coveralls.io...
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
